// <auto-generated />
using BGMNANotebookGrab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BGMNANotebookGrab.Migrations
{
    [DbContext(typeof(AlignmentVoteContext))]
    [Migration("20200317105420_AddAlignment")]
    partial class AddAlignment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("BGMNANotebookGrab.Models.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VoteId");

                    b.ToTable("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
